name: Continue on Exit Code 4

on:
  workflow_dispatch:

jobs:
  check-exit-code:
    runs-on: ubuntu-latest

    steps:
    - name: Check Exit Code
      id: check
      run: |
        # Use a heredoc to define a Bash script inline
        # This script intentionally fails with an exit code of 4
        bash <<EOF
          #!/bin/bash
          echo "Intentionally failing with exit code 4"
          exit 4
        EOF

        exit_code=$?

        # Check if the exit code is 4
        if [ $exit_code -eq 4 ]; then
          echo "Exit code is 4. Continuing to the next job."
        else
          echo "Exit code is not 4. Continuing to the next job anyway."
        fi
