name: Continue on Exit Code 4

on:
  workflow_dispatch:

jobs:
  check-exit-code:
    runs-on: ubuntu-latest

    steps:
    - name: Set Exit Code
      id: set-exit-code
      run: |
        # Define the script inline
        script_result=$(bash -c '
          #!/bin/bash
          echo "Intentionally failing with exit code 4"
          exit 4
        ')

        exit_code=$?
        echo "::set-output name=exit_code::$exit_code"
      continue-on-error: true

    - name: Check Exit Code and Set Environment Variable
      run: echo "Exit code is ${{ steps.set-exit-code.outputs.exit_code }}"
      env:
        EXIT_CODE: ${{ steps.set-exit-code.outputs.exit_code }}

  dummy-next-job:
    runs-on: ubuntu-latest
    needs: check-exit-code

    steps:
    - name: Dummy Next Job
      run: |
        if [ "${{ env.EXIT_CODE }}" -eq 4 ]; then
          echo "Exit code is 4. Continuing to the dummy next job."
        else
          echo "Exit code is not 4. Continuing to the dummy next job anyway."
        }
