name: Continue on Exit Code 4

on:
  workflow_dispatch:

jobs:
  check-exit-code:
    runs-on: ubuntu-latest

    steps:
    - name: Check Exit Code
      id: check
      run: |
        # Define the script inline
        script_result=$(bash -c '
          #!/bin/bash
          echo "Intentionally failing with exit code 4"
          exit 4
        ')

        exit_code=$?

        # Check if the exit code is 4
        if [ $exit_code -eq 4 ]; then
          echo "Exit code is 4. Continuing to the next job."
        else
          echo "Exit code is not 4. Continuing to the next job anyway."
        }

  dummy-next-job:
    runs-on: ubuntu-latest
    needs: check-exit-code

    steps:
    - name: Dummy Next Job
      run: echo "This is a dummy next job."
